let age = 17;
console.log(age);
const name = "Darina";
console.log(name);
let isStudent = true; 
console.log(isStudent);
const myString = "Правильні люди на правильному місці важливіші за правильну стратегію";
console.log(myString);
let myNumber = 3; 
myNumber = myNumber + 10;
console.log(myNumber);
let myNull = null;
console.log(myNull);
let userName = prompt("Введіть своє ім’я");
alert("Ваше ім’я: " + userName);
console.log("Тип змінної userName: " + typeof userName);
let userAnswer = confirm("Ви дійсно хочете покинути сторінку?");
console.log("Результат: " + userAnswer);
alert("Увага! Дія може бути небезпечною.");
let userConfirmed = confirm("Ви впевнені, що хочете продовжити?");
console.log("Користувач підтвердив дію: " + userConfirmed);
const hi = "Hello world";

